from jinja2 import Template


def _generate_markdown_report(title: str, content: str) -> str:
    """Generate a formatted Markdown report."""
    template = Template("""
# {{ title }}

## Generated Report

{{ content }}

---

Generated by Nexus AI Engine — Autonomous Research Agent
""")

    return template.render(title=title, content=content)


def _generate_html_report(title: str, content: str) -> str:
    """Generate a formatted HTML report."""
    template = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body { font-family: 'Inter', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
        h1 { color: #6366f1; }
        h2 { color: #8b5cf6; }
        p { line-height: 1.8; color: #333; }
        hr { border: 1px solid #e2e8f0; margin: 30px 0; }
        footer { color: #94a3b8; font-size: 14px; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    <h2>Generated Report</h2>
    <div>{{ content }}</div>
    <hr>
    <footer>Generated by Nexus AI Engine — Autonomous Research Agent</footer>
</body>
</html>
""")

    return template.render(title=title, content=content)


def _generate_code_snippet(language: str, task: str) -> str:
    """Generate a code snippet template for the given task.

    The actual code generation is handled by the LLM via the agent.
    This function provides structured formatting.
    """
    return f"""
```{language}
# Auto-generated {language} code
# Task: {task}

# Note: The full implementation is generated by the AI agent
# based on the research context and user requirements.

{task}
```
"""


def canvas_tool(output_type: str, title: str, content: str, language: str = "python") -> str:
    """Generate formatted output documents such as reports, summaries, or code.

    Use this tool when the user asks you to generate a report, create a
    document, write a summary, produce HTML output, generate markdown,
    or write code snippets. This tool takes research content and formats
    it into polished output using Jinja2 templates.

    Args:
        output_type: The format of the output. Must be one of:
            'markdown' for Markdown reports,
            'html' for HTML documents,
            'code' for code snippets.
        title: The title of the generated document or report.
        content: The main content or research data to include.
        language: Programming language for code snippets (default: python).

    Returns:
        A formatted string in the requested output format.
    """
    if output_type == "markdown":
        return _generate_markdown_report(title, content)

    elif output_type == "html":
        return _generate_html_report(title, content)

    elif output_type == "code":
        return _generate_code_snippet(language, content)

    return f"Unsupported output type: {output_type}. Use 'markdown', 'html', or 'code'."